auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 4317
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  grpc_server_max_recv_msg_size: 1.048576e+08
  grpc_server_max_send_msg_size: 1.048576e+08
  log_level: info
  grpc_server_max_concurrent_streams: 1000

common:
  path_prefix: /etc/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

querier:
  query_ingesters_within: 1m
  max_concurrent: 10

frontend:
  compress_responses: true
  log_queries_longer_than: 10s

storage_config:
  filesystem:
    directory: /etc/loki/chunks

schema_config:
  configs:
    - from: 2022-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  allow_structured_metadata: true
  retention_period: 30d
  deletion_mode: filter-and-delete
  max_entries_limit_per_query: 5000
  max_query_series: 500
  cardinality_limit: 100000
  creation_grace_period: 10m

ingester_client:
  remote_timeout: 10s
  grpc_client_config:
    max_send_msg_size: 104857600

ingester:
  wal:
    dir: /etc/loki/wal
    replay_memory_ceiling: 1GB
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_chunk_age: 2h
  chunk_idle_period: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
