auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /etc/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  filesystem:
    directory: /etc/loki/chunks

schema_config:
  configs:
    - from: 2022-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  allow_structured_metadata: true
  retention_period: 30d
  deletion_mode: filter-and-delete

ingester:
  wal:
    dir: /etc/loki/wal