common:
  storage:
    backend: filesystem
    filesystem:
      dir: /etc/mimir/data

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /etc/mimir/blocks

server:
  http_listen_port: 9009

multitenancy_enabled: true