server:
  http_listen_port: 3200
  # grpc_listen_port: 9095 # for some reason here this is not actually the port used for external comunication

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "tempo:4317"
        http:
          endpoint: "tempo:4318"

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces


compactor:
  compaction:
    compacted_block_retention: 24h

querier:
  max_concurrent_queries: 10