server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:9095
        http:
          endpoint: 0.0.0.0:3200

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    compacted_block_retention: 24h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

querier:
  max_concurrent_queries: 10

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://mimir:9009/api/v1/push
        send_exemplars: true

search:
  enabled: true